### ISSUE TITLE
Error when logging error

### ISSUE THREAD

**Issue by devdpontes** [understand/understand-js#10]
I've followed the documentation and installed the package. When triggering an error, I get the following error:

<img width="672" alt="Screenshot 2020-01-22 at 17 34 22" src="https://user-images.githubusercontent.com/7223755/72918435-90365280-3d3d-11ea-832c-6b1ef3cb12eb.png">

**Comment by aivis** [comment]
Hey @devdpontes 

Could you please double check if the `Understand.init` is called as soon as possible after the library is included in your app?

According to our testing, the error you have is only possible if the `Understand.catchErrors()` method is called before the library is initialised (`Understand.init`).

The sequence should be as follows:
1) Include the library (CDN or npm)
2) `Understand.init` 
3) `Understand.catchErrors` (this should be called only after `init`)

**Comment by devdpontes** [comment]
Hi @aivis,

I'm trying this in a React app and the `Understand.init` is called before the app is mounted. The `Understand.logError(e);` is called after a rejected XHR call, so definitely after `Understand.init`.

I'm following the docs:

```
Understand.init({
  env: 'production', // define environment
  token : 'your-input-token-from-your-account'
}).catchErrors();
```

https://www.understand.io/docs/1.0/understand-js/introduction

I've also noticed that where it says `import Understand from 'understand-js';` it should be `import Understand from '@understand/understand-js';`.

Thanks for the quick reply.

**Comment by aivis** [comment]
Thanks, @devdpontes ! I've adjusted the documentation as you suggested.

We tested the package with React app, and it worked as expected. Here is what we did:
`index.js`:
```js
import Understand from '@understand/understand-js';

Understand.init({
  token: 'your-input-token-from-your-account',
  env: 'production',
}).catchErrors();
```

and then `App.js`:
```js
componentDidMount() {
    axios.get('https://httpstat.us/400')
      .then(function (response) {
        // handle success
        console.log(response);
      })
      .catch(function (error) {
        Understand.logError(error);
      });
  }
```

The error was delivered to Understand.io as expected.

Could you please send us examples of your code? It would be really helpful in this process. Feel free to send them to `info@understand.io` if you don't want to post them here.

**Comment by devdpontes** [comment]
Never mind, it was a silly mistake on my code. The `init` was depending on the app's environment being production, so it wasn't running. 🤦‍♂ 

Since the `logError` method wasn't failing it didn't cross my mind.

Sorry for this and thank you for your time.

**Comment by aivis** [comment]
@devdpontes no problems!

We are planning to improve the error message if the package was not initialised. Instead of saying `Cannot read property 'handle' of undefined` it could explain that the `init` method was not called yet.

**Comment by devdpontes** [comment]
That would help distracted people like me. 😅 

Thanks!
